services:
  mailbox:
    # Build config
    container_name: mailbox
    build: 
      context: .
    
    # User config
    image: dydev20/mailbox:0.1
    hostname: mail.example.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "2525:2525"
    restart: on-failure
    volumes:
      - /etc/letsencrypt/live/mail.example.com:/etc/letsencrypt/live/mailbox:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      #- /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /home/vmail:/home/vmail
      - ./.domains.env:/.domains.env
    env_file:
      - path: ./.env
        required: true

