#!/bin/bash
#
DOVECOT_SSL_CONF="/etc/dovecot/conf.d/10-ssl.conf"
DOVECOT_LMTP_CONF="/etc/dovecot/conf.d/20-lmtp.conf"
POSTFIX_CONF="/etc/postfix/main.cf"

# append local_name domain cert configuration in dovecot
#
append_dovecot_localname() {
    local DOMAIN=$1
    local PATH_NAME=${2:-$DOMAIN}  # Use second argument if provided, otherwise use DOMAIN
    cat <<EOF >> "$DOVECOT_SSL_CONF"

# Added by docker entrypoint
local_name $DOMAIN {
    ssl_cert = </etc/letsencrypt/live/$PATH_NAME/fullchain.pem
    ssl_key = </etc/letsencrypt/live/$PATH_NAME/privkey.pem
}

EOF
}
#
##


# append required postmaster address for LMTP in dovecot
#
append_dovecot_lmtp_postmaster() {
    local LMTP_DOMAIN=$1
    cat <<EOF >> "$DOVECOT_LMTP_CONF"

# Added by docker entrypoint
protocol lmtp {
  postmaster_address = postmaster@$LMTP_DOMAIN   # required
}

EOF
}
#
##


# Change ownership of vmail
chown -R vmail:vmail /home/vmail

## hash files from .domains.env
# change ownership of domains config to root
chown -R root:root .domains.env
# hash postfix vmail_ssl.map text config
cp .domains.env/vmail_ssl.map /etc/postfix/vmail_ssl.map
#RUN postmap /etc/postfix/vmail_ssl.map
postmap -F hash:/etc/postfix/vmail_ssl.map
rm /etc/postfix/vmail_ssl.map
# hash vmaps text
cp .domains.env/vmaps /etc/postfix/vmaps
postmap /etc/postfix/vmaps
rm /etc/postfix/vmaps
# hash postfix sasl_passwd text
cp .domains.env/sasl_passwd /etc/postfix/sasl_passwd
postmap /etc/postfix/sasl_passwd
rm /etc/postfix/sasl_passwd
# copy dovecot passwd text
cp .domains.env/passwd /etc/dovecot/passwd
##

## Update postfix conf from hostname and env
# Use system hostname passed by --hostname
mailhost=$(hostname -f)
# Strip subdomain from hostname to use as main mail domain
maildomain=$(echo "$mailhost" | awk -F'.' '{ print $(NF-1)"."$NF }')

# set postmaster address using maildomain in dovecot lmtp conf
append_dovecot_lmtp_postmaster "$maildomain"

# set new postconf myhostname value
postconf -e "myhostname=$mailhost"
# Set relay host from passed env file
relayhost=$(echo "$RELAY_HOST")
postconf -e "relayhost=$relayhost"

## Setup SSL config in postfix and dovecot for all domains
# Use env files to get additional domains
ADDITIONAL_HOSTS=$(echo "$OTHER_HOSTS")
# add localname config for mailbox domain first
append_dovecot_localname "$mailhost" "mailbox"
# Loop through the comma-separated domains
virtualdomains = ""
virtualdomains+="${maildomain}"
IFS=, read -ra ADDITIONAL_HOST_LIST <<< "$ADDITIONAL_HOSTS"
for ADD_HOST in "${ADDITIONAL_HOST_LIST[@]}"
  do
    append_dovecot_localname "$ADD_HOST"
    ADD_DOMAIN=$(echo "$ADD_HOST" | awk -F'.' '{ print $(NF-1)"."$NF }')
    virtualdomains+=",${ADD_DOMAIN}"
done
# Add combined virtual domains to postfix conf
postconf -e "virtual_mailbox_domains=$virtualdomains"
#
##


### Final starup
#
# Finally run starup commands to launch supervisor
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

