#!/bin/bash

# Start Postfix process
/usr/sbin/postfix start &

# Start Dovecot process
/usr/sbin/dovecot -F &

# Wait for any process to exit
wait -n

# Exit with status of process that exited first
exit $?
